### ISSUE TITLE
Add a build step before running gramps CLI command

### ISSUE THREAD

**Issue by jlengstorf** [gramps-graphql/gramps#6]
The `gramps` command points to the `dist/dev/server.js` file, but doesn't force a build. This is confusing. It should either run the build before starting GrAMPS, or point to the source files and use `nodemon`.

Using `nodemon` may be preferable, because it would solve the problem of watching for changes.

**Comment by corycook** [comment]
I think that this only affects those who are developing with a locally linked version of gramps. When you `yarn` install gramps it only comes with the _/dist_ folder so there is nothing to build.

**Comment by jlengstorf** [comment]
True. It’s also kind of irrelevant now that the CLI is being pulled to its own package. I’m going to close this one.
